In [3]:
import pandas as pd
import numpy as np
import random

# Incorrect Values

In [15]:
students = []
classes_taking = []
time_wake_up = []
time_at_library = []
wake_up_times = [str(i) + random.choice([":00", ":30"]) + random.choice([" PM", " AM"]) for i in range(1,12+1)]

#create students
for i in range(1,100+1):
    students.append("Student {}".format(i))
    classes_taking.append(random.randint(1,5))
    time_wake_up.append(random.choice(wake_up_times))
    time_at_library.append(str(random.randint(0,8)) + " hours")

#create table
d = {"Students": students, "Classes Taking": classes_taking, "Time Wake Up": time_wake_up, "Time Spend at Library": time_at_library}
incorrect_table = pd.DataFrame(data=d)
incorrect_table = incorrect_table[["Students","Classes Taking","Time Wake Up","Time Spend at Library"]]
incorrect_table

       Students  Classes Taking Time Wake Up Time Spend at Library
0     Student 1               3      7:00 AM               3 hours
1     Student 2               1      6:00 AM               1 hours
2     Student 3               5      2:00 AM               3 hours
3     Student 4               4      3:00 AM               6 hours
4     Student 5               4      5:30 PM               0 hours
5     Student 6               4      9:00 AM               5 hours
6     Student 7               5      3:00 AM               6 hours
7     Student 8               4     11:00 AM               4 hours
8     Student 9               2      4:30 PM               3 hours
9    Student 10               4     11:00 AM               6 hours
10   Student 11               4      4:30 PM               2 hours
11   Student 12               4      2:00 AM               0 hours
12   Student 13               5      2:00 AM               4 hours
13   Student 14               1     11:00 AM               0 hours
14   Student 15               3      6:00 AM               3 hours
15   Student 16               3     12:30 PM               2 hours
16   Student 17               1     11:00 AM               7 hours
17   Student 18               2      9:00 AM               0 hours
18   Student 19               3      1:30 PM               8 hours
19   Student 20               4     12:30 PM               5 hours
20   Student 21               1      1:30 PM               1 hours
21   Student 22               1      8:00 PM               4 hours
22   Student 23               1      8:00 PM               5 hours
23   Student 24               1     12:30 PM               0 hours
24   Student 25               2      2:00 AM               8 hours
25   Student 26               1      6:00 AM               6 hours
26   Student 27               5      3:00 AM               7 hours
27   Student 28               1     12:30 PM               3 hours
28   Student 29               3      1:30 PM               7 hours
29   Student 30               3      4:30 PM               5 hours
..          ...             ...          ...                   ...
70   Student 71               4      3:00 AM               7 hours
71   Student 72               5      2:00 AM               5 hours
72   Student 73               1     12:30 PM               4 hours
73   Student 74               2      9:00 AM               1 hours
74   Student 75               2      1:30 PM               8 hours
75   Student 76               2      5:30 PM               5 hours
76   Student 77               3      3:00 AM               5 hours
77   Student 78               4      5:30 PM               2 hours
78   Student 79               3      7:00 AM               3 hours
79   Student 80               1      4:30 PM               1 hours
80   Student 81               5      8:00 PM               7 hours
81   Student 82               1     11:00 AM               6 hours
82   Student 83               1      7:00 AM               1 hours
83   Student 84               3      6:00 AM               6 hours
84   Student 85               3     12:30 PM               2 hours
85   Student 86               1      3:00 AM               5 hours
86   Student 87               4     12:30 PM               7 hours
87   Student 88               4      8:00 PM               1 hours
88   Student 89               1      9:00 AM               3 hours
89   Student 90               3     11:00 AM               1 hours
90   Student 91               1     10:30 PM               2 hours
91   Student 92               4      8:00 PM               8 hours
92   Student 93               2     12:30 PM               1 hours
93   Student 94               1     10:30 PM               1 hours
94   Student 95               3      3:00 AM               3 hours
95   Student 96               4     11:00 AM               5 hours
96   Student 97               5      6:00 AM               2 hours
97   Student 98               2     10:30 PM               8 hours
98   Student 99               5      9:00 AM               2 hours
99  Student 100               4      6:00 AM               7 hours

[100 rows x 4 columns]

In [22]:
#lets mess up some values for Time Spent at Library
for i in range(25):
    rand_row = random.randint(0,99)
    incorrect_table.loc[rand_row,"Time Spend at Library"] = random.choice(["Uh", "None", "", "Many"])

#mess up Time Wake Up
for i in range(32):
    rand_row = random.randint(0,99)
    incorrect_table.loc[rand_row, "Time Wake Up"] = random.choice(["Never", "Morning", "Team No Sleep"])

#mess up Classes Taking
for i in range(40):
    rand_row = random.randint(0,99)
    incorrect_table.loc[rand_row, "Classes Taking"] = random.choice(["I don't go here lol", "None", "Yes"])
    
incorrect_table

       Students       Classes Taking   Time Wake Up Time Spend at Library
0     Student 1                    3        Morning               3 hours
1     Student 2                    1        6:00 AM                  Many
2     Student 3                  Yes        2:00 AM                  None
3     Student 4  I don't go here lol        3:00 AM                  Many
4     Student 5                  Yes          Never
5     Student 6  I don't go here lol        9:00 AM                  None
6     Student 7                  Yes          Never                  Many
7     Student 8                  Yes       11:00 AM               4 hours
8     Student 9                    2        4:30 PM
9    Student 10                  Yes        Morning                    Uh
10   Student 11                    4          Never                    Uh
11   Student 12                  Yes        Morning               0 hours
12   Student 13                  Yes          Never               4 hours
13   Student 14  I don't go here lol       11:00 AM               0 hours
14   Student 15                  Yes        6:00 AM                  None
15   Student 16                    3        Morning               2 hours
16   Student 17  I don't go here lol        Morning                  None
17   Student 18                  Yes        9:00 AM                  Many
18   Student 19                    3        1:30 PM                    Uh
19   Student 20                    4          Never               5 hours
20   Student 21                    1        Morning               1 hours
21   Student 22                    1        Morning               4 hours
22   Student 23                    1        8:00 PM
23   Student 24                  Yes  Team No Sleep                    Uh
24   Student 25                    2        2:00 AM               8 hours
25   Student 26                    1  Team No Sleep               6 hours
26   Student 27                  Yes        3:00 AM               7 hours
27   Student 28                 None  Team No Sleep               3 hours
28   Student 29                  Yes        1:30 PM
29   Student 30                 None  Team No Sleep               5 hours
..          ...                  ...            ...                   ...
70   Student 71                  Yes        3:00 AM               7 hours
71   Student 72                  Yes  Team No Sleep                    Uh
72   Student 73                    1  Team No Sleep                    Uh
73   Student 74                    2  Team No Sleep               1 hours
74   Student 75                    2        1:30 PM
75   Student 76                  Yes        5:30 PM                    Uh
76   Student 77                 None          Never               5 hours
77   Student 78  I don't go here lol  Team No Sleep                    Uh
78   Student 79                    3        Morning                    Uh
79   Student 80                    1        4:30 PM                    Uh
80   Student 81                 None          Never               7 hours
81   Student 82  I don't go here lol        Morning               6 hours
82   Student 83                 None  Team No Sleep
83   Student 84                  Yes        6:00 AM                  None
84   Student 85  I don't go here lol  Team No Sleep                    Uh
85   Student 86                  Yes  Team No Sleep
86   Student 87                    4        Morning
87   Student 88                  Yes        8:00 PM
88   Student 89  I don't go here lol        9:00 AM               3 hours
89   Student 90                 None        Morning               1 hours
90   Student 91                    1  Team No Sleep                  None
91   Student 92  I don't go here lol        Morning               8 hours
92   Student 93  I don't go here lol       12:30 PM                  None
93   Student 94                    1       10:30 PM               1 hours
94   Student 95                    3          Never               3 hours
95   Student 96  I don't go here lol       11:00 AM               5 hours
96   Student 97                  Yes        6:00 AM                  Many
97   Student 98                    2       10:30 PM               8 hours
98   Student 99                    5        9:00 AM                  None
99  Student 100                    4        6:00 AM               7 hours

[100 rows x 4 columns]